// @generated by protobuf-ts 2.11.0 with parameter client_grpc1,server_grpc1
// @generated from protobuf file "product_catalog.proto" (package "product_catalog", syntax proto3)
// tslint:disable
import { ProductCatalogService } from "./product_catalog";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { GetProductListResponse } from "./product_catalog";
import type { GetProductListRequest } from "./product_catalog";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service product_catalog.ProductCatalogService
 */
export interface IProductCatalogServiceClient {
    /**
     * Add other methods like GetProductById, CreateProduct, etc. as needed
     *
     * @generated from protobuf rpc: GetProductList
     */
    getProductList(input: GetProductListRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetProductListResponse) => void): grpc.ClientUnaryCall;
    getProductList(input: GetProductListRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetProductListResponse) => void): grpc.ClientUnaryCall;
    getProductList(input: GetProductListRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetProductListResponse) => void): grpc.ClientUnaryCall;
    getProductList(input: GetProductListRequest, callback: (err: grpc.ServiceError | null, value?: GetProductListResponse) => void): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service product_catalog.ProductCatalogService
 */
export class ProductCatalogServiceClient extends grpc.Client implements IProductCatalogServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Add other methods like GetProductById, CreateProduct, etc. as needed
     *
     * @generated from protobuf rpc: GetProductList
     */
    getProductList(input: GetProductListRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetProductListResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetProductListResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetProductListResponse) => void)): grpc.ClientUnaryCall {
        const method = ProductCatalogService.methods[0];
        return this.makeUnaryRequest<GetProductListRequest, GetProductListResponse>(`/${ProductCatalogService.typeName}/${method.name}`, (value: GetProductListRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetProductListResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
