// @generated by protobuf-ts 2.11.0 with parameter client_grpc1,server_grpc1
// @generated from protobuf file "product_catalog.proto" (package "product_catalog", syntax proto3)
// tslint:disable
import { GetProductListResponse } from "./product_catalog";
import { GetProductListRequest } from "./product_catalog";
import type * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service product_catalog.ProductCatalogService
 */
export interface IProductCatalogService extends grpc.UntypedServiceImplementation {
    /**
     * Add other methods like GetProductById, CreateProduct, etc. as needed
     *
     * @generated from protobuf rpc: GetProductList
     */
    getProductList: grpc.handleUnaryCall<GetProductListRequest, GetProductListResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service product_catalog.ProductCatalogService.
 *
 * Usage: Implement the interface IProductCatalogService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IProductCatalogService = ...
 * server.addService(productCatalogServiceDefinition, service);
 * ```
 */
export const productCatalogServiceDefinition: grpc.ServiceDefinition<IProductCatalogService> = {
    getProductList: {
        path: "/product_catalog.ProductCatalogService/GetProductList",
        originalName: "GetProductList",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetProductListResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetProductListRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetProductListResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetProductListRequest.toBinary(value))
    }
};
